### PR TITLE
Allow usage of zend-expressive-helpers 4.0

### PR DESCRIPTION
**Pull request by weierophinney**
The API used by the Plates renderer is still compatible in version 4.0.

### CODE REVIEW

**Comment by michalbundyra** [comment]
Should we update somehow travis configuration to run tests with zend-expressive-helpers v2, v3 and v4 as it supports all 3 versions?

I think this PR should contain also updated lock file.

**Comment by weierophinney** [comment]
> Should we update somehow travis configuration to run tests with zend-expressive-helpers v2, v3 and v4 as it supports all 3 versions?
> 
> I think this PR should contain also updated lock file.

By _not_ updating the lock file, we're effectively testing against all three zend-expressive-helpers versions. :smile:. We may want to change that in the future, but we know _now_ that it works across each.

**Comment by michalbundyra** [comment]
> By not updating the lock file, we're effectively testing against all three zend-expressive-helpers versions.

Yes, but this is tricky way, and it's gonna work only when we remember to not update the lock file (or this package in lock file). What more, now we get also composer warning:
https://travis-ci.org/zendframework/zend-expressive-platesrenderer/jobs/210736039#L191
because hash in composer.lock is not updated and change in composer.json has been made.

It's not a big deal, but probably the same/similar situation we can have also with other packages, so will be good to find the right solution for all of them.

**Comment by weierophinney** [comment]
@webimpress I've added additional builds to the matrix that will require zend-expressive-helpers with the `^3.0.1` constraint, and updated the `composer.lock`. Looks like the build will work at this point.

**Pull request merged**
