### PR TITLE
Allow injection of Plates Extensions

### PR DESCRIPTION
**Pull request by stormwild**

### CODE REVIEW

**Comment by weierophinney** [comment]
Per #5, there are a few things still:
- We need tests!
- And this comment: "I'm wondering if it might make sense to also allow loading of arbitrary extensions, like we did in Twig? We could still load the PlatesExtension as done here — or provide a factory for it — but that might provide a bit more flexibility with regards to this factory."

Thanks in advance!

**Comment by stormwild** [comment]
So sorry could not allocate time. Still need to study making the unit tests.

**Comment by weierophinney** [comment]
Please take a look at #7; I've already done it. ;-)

**Comment by stormwild** [comment]
Superseded by https://github.com/zendframework/zend-expressive-platesrenderer/pull/7 thanks :)

**Pull request closed without merging**
